export default function (target) {
  return [
      // 能源基地
        { columnName: 'energy_BSM', prop: 'BSM', label: '标识码', align: 'center', width: 100 },
        { columnName: 'energy_YSDM', prop: 'YSDM', label: '要素代码', align: 'center', minWidth: 100 },
        { columnName: 'energy_JDBH', prop: 'JDBH', label: '基地编号', align: 'center', width: 100 },
        { columnName: 'energy_JDMC', prop: 'JDMC', label: '基地名称', align: 'center', width: 100 },
        { columnName: 'energy_SZXZQ', prop: 'SZXZQ', label: '所在行政区', align: 'center', width: 100 },
        { columnName: 'energy_JDMJ', prop: 'JDMJ', label: '基地面积', align: 'center', width: 100 },
        { columnName: 'energy_GDZB', prop: 'GDZB', label: '拐点坐标', align: 'center', width: 100 },
        { columnName: 'energy_ZYKCDM', prop: 'ZYKCDM', label: '主要矿产代码', align: 'center', width: 100 },
        { columnName: 'energy_ZYKCMC', prop: 'ZYKCMC', label: '主要矿产名称', align: 'center', width: 100 },
        { columnName: 'energy_YSTKQZS', prop: 'YSTKQZS', label: '已设探矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'energy_NSTKQZS', prop: 'NSTKQZS', label: '拟设探矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'energy_YSCKQZS', prop: 'YSCKQZS', label: '已设采矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'energy_YSKCGM', prop: 'YSKCGM', label: '已设采矿权设计开采规模', align: 'center', minWidth: 180 },
        { columnName: 'energy_BZ', prop: 'BZ', label: '备注', align: 'center', width: 100 },
        { columnName: 'energy_GHQ', prop: 'GHQ', label: '规划期', align: 'center', width: 100 },
        { columnName: 'energy_GHBZJB', prop: 'GHBZJB', label: '规划编制级别', align: 'center', width: 100 },
    // 规划矿区
        { columnName: 'plan_BSM', prop: 'BSM', label: '标识码', align: 'center', width: 100 },
        { columnName: 'plan_YSDM', prop: 'YSDM', label: '要素代码', align: 'center', width: 100 },
        { columnName: 'plan_GHKQBH', prop: 'GHKQBH', label: '规划矿区编号', align: 'center', width: 100 },
        { columnName: 'plan_GHKQMC', prop: 'GHKQMC', label: '规划矿区名称', align: 'center', width: 100 },
        { columnName: 'plan_SZXZQ', prop: 'SZXZQ', label: '所在行政区', align: 'center', width: 100 },
        { columnName: 'plan_KQMJ', prop: 'KQMJ', label: '矿区面积', align: 'center', width: 100 },
        { columnName: 'plan_GDZB', prop: 'GDZB', label: '拐点坐标', align: 'center', width: 100 },
        { columnName: 'plan_ZYKCDM', prop: 'ZYKCDM', label: '主要矿产代码', align: 'center', width: 100 },
        { columnName: 'plan_ZYKCMC', prop: 'ZYKCMC', label: '主要矿产名称', align: 'center', width: 100 },
        { columnName: 'plan_ZYKCTMZYL', prop: 'ZYKCTMZYL', label: '主要矿产探明资源量', align: 'center', minWidth: 140 },
        { columnName: 'plan_ZYKCKZZYL', prop: 'ZYKCKZZYL', label: '主要矿产控制资源量', align: 'center', minWidth: 140 },
        { columnName: 'plan_ZYKCTDZYL', prop: 'ZYKCTDZYL', label: '主要矿产推断资源量', align: 'center', minWidth: 140 },
        { columnName: 'plan_YSTKQZS', prop: 'YSTKQZS', label: '已设探矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'plan_NSTKQZS', prop: 'NSTKQZS', label: '拟设探矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'plan_YSCKQZS', prop: 'YSCKQZS', label: '已设采矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'plan_YSKCGM', prop: 'YSKCGM', label: '已设采矿权设计开采规模', align: 'center', minWidth: 180 },
        { columnName: 'plan_NSCKQZS', prop: 'NSCKQZS', label: '拟设采矿权总数', align: 'center', width: 140 },
        // 资源保护区
        { columnName: 'res_BSM', prop: 'BSM', label: '标识码', align: 'center', width: 100 },
        { columnName: 'res_YSDM', prop: 'YSDM', label: '要素代码', align: 'center', width: 100 },
        { columnName: 'res_KCBHQBH', prop: 'KCBHQBH', label: '矿产资源保护区编号', align: 'center', width: 100 },
        { columnName: 'res_KCBHQMC', prop: 'KCBHQMC', label: '矿产资源保护区名称', align: 'center', width: 100 },
        { columnName: 'res_SZXZQ', prop: 'SZXZQ', label: '所在行政区', align: 'center', width: 100 },
        { columnName: 'res_KCBHQMJ', prop: 'KCBHQMJ', label: '矿产资源保护区面积', align: 'center', width: 100 },
        { columnName: 'res_GDZB', prop: 'GDZB', label: '拐点坐标', align: 'center', width: 100 },
        { columnName: 'res_ZYKCDM', prop: 'ZYKCDM', label: '主要矿产代码', align: 'center', width: 100 },
        { columnName: 'res_ZYKCMC', prop: 'ZYKCMC', label: '主要矿产名称', align: 'center', width: 100 },
        { columnName: 'res_ZYKCTMZYL', prop: 'ZYKCTMZYL', label: '主要矿产探明资源量', align: 'center', minWidth: 140 },
        { columnName: 'res_ZYKCKZZYL', prop: 'ZYKCKZZYL', label: '主要矿产控制资源量', align: 'center', minWidth: 140 },
        { columnName: 'res_ZYKCTDZYL', prop: 'ZYKCTDZYL', label: '主要矿产推断资源量', align: 'center', minWidth: 140 },
        { columnName: 'res_YSCKQZS', prop: 'YSCKQZS', label: '已设采矿权总数', align: 'center', minWidth: 140 },

        // 资源勘测区域
        { columnName: 'area_BSM', prop: 'BSM', label: '标识码', align: 'center', width: 100 },
        { columnName: 'area_YSDM', prop: 'YSDM', label: '要素代码', align: 'center', minWidth: 100 },
        { columnName: 'area_FQBH', prop: 'FQBH', label: '分区编号', align: 'center', width: 100 },
        { columnName: 'area_FQMC', prop: 'FQMC', label: '分区名称', align: 'center', width: 100 },
        { columnName: 'area_SZXZQ', prop: 'SZXZQ', label: '所在行政区', align: 'center', width: 100 },
        { columnName: 'area_FQMJ', prop: 'FQMJ', label: '分区面积', align: 'center', width: 100 },
        { columnName: 'area_GDZB', prop: 'GDZB', label: '拐点坐标', align: 'center', width: 100 },
        { columnName: 'area_ZYKCDM', prop: 'ZYKCDM', label: '主要矿产代码', align: 'center', width: 100 },
        { columnName: 'area_ZYKCMC', prop: 'ZYKCMC', label: '主要矿产名称', align: 'center', width: 100 },
        { columnName: 'area_YSTKQZS', prop: 'YSTKQZS', label: '已设探矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'area_NSTKQZS', prop: 'NSTKQZS', label: '拟设探矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'area_BZ', prop: 'BZ', label: '备注', align: 'center', width: 100 },
        { columnName: 'area_GHQ', prop: 'GHQ', label: '规划期', align: 'center', width: 100 },
        { columnName: 'area_GHBZJB', prop: 'GHBZJB', label: '规划编制级别', align: 'center', width: 100 },
        // 勘测区块
        { columnName: 'modules_BSM', prop: 'BSM', label: '标识码', align: 'center', width: 100 },
        { columnName: 'modules_YSDM', prop: 'YSDM', label: '要素代码', align: 'center', minWidth: 100 },
        { columnName: 'modules_QKBH', prop: 'QKBH', label: '区块编号', align: 'center', width: 100 },
        { columnName: 'modules_QKMC', prop: 'QKMC', label: '区块名称', align: 'center', width: 100 },
        { columnName: 'modules_KZDM', prop: 'KZDM', label: '勘查主矿种名称', align: 'center', width: 100 },
        { columnName: 'modules_KZMC', prop: 'KZMC', label: '勘查主矿种代码', align: 'center', width: 100 },
        { columnName: 'modules_QKMJ', prop: 'QKMJ', label: '区块面积', align: 'center', width: 100 },
        { columnName: 'modules_GDZB', prop: 'GDZB', label: '拐点坐标', align: 'center', width: 100 },
        { columnName: 'modules_QTKZDM', prop: 'QTKZDM', label: '其他勘查矿种代码', align: 'center', width: 100 },
        { columnName: 'modules_QTKZMC', prop: 'QTKZMC', label: '其他勘查矿种名称', align: 'center', width: 100 },
        { columnName: 'modules_KCCD', prop: 'KCCD', label: '现有勘查程度', align: 'center', minWidth: 140 },
        { columnName: 'modules_NSKCJD', prop: 'NSKCJD', label: '拟设探矿权勘查阶段', align: 'center', minWidth: 140 },
        { columnName: 'modules_TFSX', prop: 'TFSX', label: '投放时序', align: 'center', minWidth: 140 },
        { columnName: 'modules_BZ', prop: 'BZ', label: '备注', align: 'center', width: 100 },
        { columnName: 'modules_GHQ', prop: 'GHQ', label: '规划期', align: 'center', width: 100 },
        { columnName: 'modules_GHBZJB', prop: 'GHBZJB', label: '规划编制级别', align: 'center', width: 100 },
        // 开采规划区
        { columnName: 'IM_BSM', prop: 'BSM', label: '标识码', align: 'center', width: 100 },
        { columnName: 'IM_YSDM', prop: 'YSDM', label: '要素代码', align: 'center', minWidth: 100 },
        { columnName: 'IM_QKBH', prop: 'QKBH', label: '区块编号', align: 'center', width: 100 },
        { columnName: 'IM_QKMC', prop: 'QKMC', label: '区块名称', align: 'center', width: 100 },
        { columnName: 'IM_QKMJ', prop: 'QKMJ', label: '区块面积', align: 'center', width: 100 },
        { columnName: 'IM_KZDM', prop: 'KZDM', label: '开采主矿种代码', align: 'center', width: 100 },
        { columnName: 'IM_KZMC', prop: 'KZMC', label: '开采主矿种名称', align: 'center', width: 100 },
        { columnName: 'IM_ZLKZKZDM', prop: 'ZLKZKZDM', label: '涉及总量控制矿种代码', align: 'center', width: 100 },
        { columnName: 'IM_ZLKZKZMC', prop: 'ZLKZKZMC', label: '涉及总量控制矿种名称', align: 'center', width: 100 },
        { columnName: 'IM_GDZB', prop: 'GDZB', label: '拐点坐标', align: 'center', minWidth: 140 },
        { columnName: 'IM_ZYLDW', prop: 'ZYLDW', label: '资源量单位', align: 'center', minWidth: 140 },
        { columnName: 'IM_TMZYL', prop: 'TMZYL', label: '开采主矿种探明资源量', align: 'center', minWidth: 140 },
        { columnName: 'IM_KZZYL', prop: 'KZZYL', label: '开采主矿种控制资源量', align: 'center', minWidth: 140 },
        { columnName: 'IM_TDZYL', prop: 'TDZYL', label: '开采主矿种推断资源量', align: 'center', minWidth: 140 },
        { columnName: 'IM_QTKZJTMZYL', prop: 'QTKZJTMZYL', label: '其他开采矿种及探明资源量', align: 'center', minWidth: 140 },
        { columnName: 'IM_QTKZJKZZYL', prop: 'QTKZJKZZYL', label: '其他开采矿种及控制资源量', align: 'center', minWidth: 140 },
        { columnName: 'IM_QTKZJTDZYL', prop: 'QTKZJTDZYL', label: '其他开采矿种及推断资源量', align: 'center', minWidth: 140 },
        { columnName: 'IM_TFSX', prop: 'TFSX', label: '投放时序', align: 'center', minWidth: 140 },
        { columnName: 'IM_BZ', prop: 'BZ', label: '备注', align: 'center', width: 100 },
        { columnName: 'IM_GHQ', prop: 'GHQ', label: '规划期', align: 'center', width: 100 },
        { columnName: 'IM_GHBZJB', prop: 'GHBZJB', label: '规划编制级别', align: 'center', width: 100 }

  ]
}
