export default function (target) {
  return [
      // 能源基地
        { columnName: 'energy_BSM', prop: 'biaoshima', label: '标识码', align: 'center', width: 100 },
        { columnName: 'energy_YSDM', prop: 'yaosudaima', label: '要素代码', align: 'center', minWidth: 100 },
        { columnName: 'energy_JDBH', prop: 'jidibianhao', label: '基地编号', align: 'center', width: 100 },
        { columnName: 'energy_JDMC', prop: 'jidimingcheng', label: '基地名称', align: 'center', width: 100 },
        { columnName: 'energy_SZXZQ', prop: 'xingzhengqu', label: '所在行政区', align: 'center', width: 100 },
        { columnName: 'energy_JDMJ', prop: 'jidimianji', label: '基地面积', align: 'center', width: 100 },
        { columnName: 'energy_GDZB', prop: 'guaidianzuobiao', label: '拐点坐标', align: 'center', width: 100 },
        { columnName: 'energy_ZYKCDM', prop: 'zhuyaokuangchandm', label: '主要矿产代码', align: 'center', width: 100 },
        { columnName: 'energy_ZYKCMC', prop: 'zhuyaokuangchan', label: '主要矿产名称', align: 'center', width: 100 },
        { columnName: 'energy_YSTKQZS', prop: 'yitouzongshu', label: '已设探矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'energy_NSTKQZS', prop: 'nishetankuangquanzongs', label: '拟设探矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'energy_YSCKQZS', prop: 'yishecaikuangquanzs', label: '已设采矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'energy_YSKCGM', prop: 'yishecaikuanggm', label: '已设采矿权设计开采规模', align: 'center', minWidth: 180 },
        { columnName: 'energy_BZ', prop: 'remarks', label: '备注', align: 'center', width: 100 },
        { columnName: 'energy_GHQ', prop: 'guihuaqi', label: '规划期', align: 'center', width: 100 },
        { columnName: 'energy_GHBZJB', prop: 'guihualevel', label: '规划编制级别', align: 'center', width: 100 },
    // 规划矿区
        { columnName: 'plan_BSM', prop: 'biaoshima', label: '标识码', align: 'center', width: 100 },
        { columnName: 'plan_YSDM', prop: 'yaosudaima', label: '要素代码', align: 'center', width: 100 },
        { columnName: 'plan_GHKQBH', prop: 'guihuabh', label: '规划矿区编号', align: 'center', width: 100 },
        { columnName: 'plan_GHKQMC', prop: 'guihuakuangqu', label: '规划矿区名称', align: 'center', width: 100 },
        { columnName: 'plan_SZXZQ', prop: 'suoshuxzq', label: '所在行政区', align: 'center', width: 100 },
        { columnName: 'plan_KQMJ', prop: 'kuangqumj', label: '矿区面积', align: 'center', width: 100 },
        { columnName: 'plan_GDZB', prop: 'guaidian', label: '拐点坐标', align: 'center', width: 100 },
        { columnName: 'plan_ZYKCDM', prop: 'zhuyaokcdm', label: '主要矿产代码', align: 'center', width: 100 },
        { columnName: 'plan_ZYKCMC', prop: 'zhuyaokuangchanming', label: '主要矿产名称', align: 'center', width: 100 },
        { columnName: 'plan_ZYKCMC2', prop: 'zhuyaokcming', label: '主要矿产名称', align: 'center', width: 100 },
        { columnName: 'plan_ZYKCTMZYL', prop: 'tanmingzyl', label: '主要矿产探明资源量', align: 'center', minWidth: 140 },
        { columnName: 'plan_ZYKCKZZYL', prop: 'kongzhizyl', label: '主要矿产控制资源量', align: 'center', minWidth: 140 },
        { columnName: 'plan_ZYKCTDZYL', prop: 'tuiduanzyl', label: '主要矿产推断资源量', align: 'center', minWidth: 140 },
        { columnName: 'plan_YSTKQZS', prop: 'yitoukqzs', label: '已设探矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'plan_NSTKQZS', prop: 'nitoukuangquan', label: '拟设探矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'plan_YSCKQZS', prop: 'yitoukuangquan', label: '已设采矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'plan_YSKCGM', prop: 'yishecaikuanggm', label: '已设采矿权设计开采规模', align: 'center', minWidth: 180 },
        { columnName: 'plan_NSCKQZS', prop: 'nishecaik', label: '拟设采矿权总数', align: 'center', width: 140 },
        // 资源保护区
        { columnName: 'res_BSM', prop: 'BSM', label: '标识码', align: 'center', width: 100 },
        { columnName: 'res_YSDM', prop: 'YSDM', label: '要素代码', align: 'center', width: 100 },
        { columnName: 'res_KCBHQBH', prop: 'KCBHQBH', label: '矿产资源保护区编号', align: 'center', width: 100 },
        { columnName: 'res_KCBHQMC', prop: 'KCBHQMC', label: '矿产资源保护区名称', align: 'center', width: 100 },
        { columnName: 'res_SZXZQ', prop: 'SZXZQ', label: '所在行政区', align: 'center', width: 100 },
        { columnName: 'res_KCBHQMJ', prop: 'KCBHQMJ', label: '矿产资源保护区面积', align: 'center', width: 100 },
        { columnName: 'res_GDZB', prop: 'GDZB', label: '拐点坐标', align: 'center', width: 100 },
        { columnName: 'res_ZYKCDM', prop: 'ZYKCDM', label: '主要矿产代码', align: 'center', width: 100 },
        { columnName: 'res_ZYKCMC', prop: 'ZYKCMC', label: '主要矿产名称', align: 'center', width: 100 },
        { columnName: 'res_ZYKCTMZYL', prop: 'ZYKCTMZYL', label: '主要矿产探明资源量', align: 'center', minWidth: 140 },
        { columnName: 'res_ZYKCKZZYL', prop: 'ZYKCKZZYL', label: '主要矿产控制资源量', align: 'center', minWidth: 140 },
        { columnName: 'res_ZYKCTDZYL', prop: 'ZYKCTDZYL', label: '主要矿产推断资源量', align: 'center', minWidth: 140 },
        { columnName: 'res_YSCKQZS', prop: 'YSCKQZS', label: '已设采矿权总数', align: 'center', minWidth: 140 },

        // 资源勘测区域
        { columnName: 'area_BSM', prop: 'biaoshima', label: '标识码', align: 'center', width: 100 },
        { columnName: 'area_YSDM', prop: 'yaosudaima', label: '要素代码', align: 'center', minWidth: 100 },
        { columnName: 'area_FQBH', prop: 'fenquhao', label: '分区编号', align: 'center', width: 100 },
        { columnName: 'area_FQMC', prop: 'fenquming', label: '分区名称', align: 'center', width: 100 },
        { columnName: 'area_SZXZQ', prop: 'suozaixingzhengqu', label: '所在行政区', align: 'center', width: 100 },
        { columnName: 'area_FQMJ', prop: 'fenqumj', label: '分区面积', align: 'center', width: 100 },
        { columnName: 'area_FQMJ2', prop: 'fenqumianji', label: '分区面积', align: 'center', width: 100 },
        { columnName: 'area_GDZB', prop: 'guaidianzuobiao', label: '拐点坐标', align: 'center', width: 100 },
        { columnName: 'area_ZYKCDM', prop: 'zhuyaokuangchan', label: '主要矿产代码', align: 'center', width: 100 },
        { columnName: 'area_ZYKCMC', prop: 'zhuyaokcmingcheng', label: '主要矿产名称', align: 'center', width: 100 },
        { columnName: 'area_YSTKQZS', prop: 'yitoukqzongshu', label: '已设探矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'area_NSTKQZS', prop: 'nitoukuangquanzongshu', label: '拟设探矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'area_BZ', prop: 'remarks', label: '备注', align: 'center', width: 100 },
        { columnName: 'area_GHQ', prop: 'guihuaqi', label: '规划期', align: 'center', width: 100 },
        { columnName: 'area_GHBZJB', prop: 'guaihualevel', label: '规划编制级别', align: 'center', width: 100 },
        // 开采规划tuiduanliang
        { columnName: 'areas_BSM', prop: 'biaoshima', label: '标识码', align: 'center', width: 100 },
        { columnName: 'areas_YSDM', prop: 'yaosudaima', label: '要素代码', align: 'center', minWidth: 100 },
        { columnName: 'areas_FQBH', prop: 'fenquhao', label: '分区编号', align: 'center', width: 100 },
        { columnName: 'areas_FQMC', prop: 'fenquming', label: '分区名称', align: 'center', width: 100 },
        { columnName: 'areas_SZXZQ', prop: 'suozaixzqu', label: '所在行政区', align: 'center', width: 100 },
        { columnName: 'areas_FQMJ2', prop: 'fenqumianji', label: '分区面积', align: 'center', width: 100 },
        { columnName: 'areas_GDZB', prop: 'guaidianzuobiao', label: '拐点坐标', align: 'center', width: 100 },
        { columnName: 'areas_TMZYL', prop: 'zhuyaotanmingliang', label: '开采主矿种探明资源量', align: 'center', minWidth: 140 },
        { columnName: 'areas_KZZYL', prop: 'zhuyaokongzhiliang', label: '开采主矿种控制资源量', align: 'center', minWidth: 140 },
        { columnName: 'areas_TDZYL', prop: 'tuiduanliang', label: '开采主矿种推断资源量', align: 'center', minWidth: 140 },
        { columnName: 'areas_ZYKCDM', prop: 'zhuyaokcma', label: '主要矿产代码', align: 'center', width: 100 },
        { columnName: 'areas_ZYKCMC', prop: 'zhuyaokcming', label: '主要矿产名称', align: 'center', width: 100 },
        { columnName: 'areas_YSTKQZS', prop: 'yishekqshu', label: '已设探矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'areas_NSTKQZS', prop: 'nishekqshu', label: '拟设探矿权总数', align: 'center', minWidth: 140 },
        { columnName: 'areas_BZ', prop: 'remarks', label: '备注', align: 'center', width: 100 },
        { columnName: 'areas_GHQ', prop: 'guihuadate', label: '规划期', align: 'center', width: 100 },
        { columnName: 'areas_GHBZJB', prop: 'guaihualevel', label: '规划编制级别', align: 'center', width: 100 },
        // 勘测区块
        { columnName: 'modules_BSM', prop: 'biaoshima', label: '标识码', align: 'center', width: 100 },
        { columnName: 'modules_YSDM', prop: 'yaosudaima', label: '要素代码', align: 'center', minWidth: 100 },
        { columnName: 'modules_QKBH', prop: 'qukuaihao', label: '区块编号', align: 'center', width: 100 },
        { columnName: 'modules_QKMC', prop: 'qukuaiming', label: '区块名称', align: 'center', width: 100 },
        { columnName: 'modules_KZDM', prop: 'kanchazhukuangming', label: '勘查主矿种名称', align: 'center', width: 100 },
        { columnName: 'modules_KZMC', prop: 'kanchazhukuangzhongdm', label: '勘查主矿种代码', align: 'center', width: 100 },
        { columnName: 'modules_QKMJ', prop: 'qukuaimianji', label: '区块面积', align: 'center', width: 100 },
        { columnName: 'modules_GDZB', prop: 'guaidianzuobiao', label: '拐点坐标', align: 'center', width: 100 },
        { columnName: 'modules_QTKZDM', prop: 'qitakckuangdaima', label: '其他勘查矿种代码', align: 'center', width: 100 },
        { columnName: 'modules_QTKZMC', prop: 'qitakcming', label: '其他勘查矿种名称', align: 'center', width: 100 },
        { columnName: 'modules_KCCD', prop: 'xianyouchengdu', label: '现有勘查程度', align: 'center', minWidth: 140 },
        { columnName: 'modules_NSKCJD', prop: 'nishekcjieduan', label: '拟设探矿权勘查阶段', align: 'center', minWidth: 140 },
        { columnName: 'modules_TFSX', prop: 'toufangshixu', label: '投放时序', align: 'center', minWidth: 140 },
        { columnName: 'modules_BZ', prop: 'remarks', label: '备注', align: 'center', width: 100 },
        { columnName: 'modules_GHQ', prop: 'xianyouguihuaqi', label: '规划期', align: 'center', width: 100 },
        { columnName: 'modules_GHBZJB', prop: 'guihualevel', label: '规划编制级别', align: 'center', width: 100 },
        // 开采规划区
        { columnName: 'IM_BSM', prop: 'biaoshima', label: '标识码', align: 'center', width: 100 },
        { columnName: 'IM_YSDM', prop: 'yaosudaima', label: '要素代码', align: 'center', minWidth: 100 },
        { columnName: 'IM_QKBH', prop: 'quyubianhao', label: '区块编号', align: 'center', width: 100 },
        { columnName: 'IM_QKMC', prop: 'qukuangname', label: '区块名称', align: 'center', width: 100 },
        { columnName: 'IM_QKMJ', prop: 'qukuaimj', label: '区块面积', align: 'center', width: 100 },
        { columnName: 'IM_KZDM', prop: 'kaicaizhukuangdm', label: '开采主矿种代码', align: 'center', width: 100 },
        { columnName: 'IM_KZMC', prop: 'kaicaizhukuangmc', label: '开采主矿种名称', align: 'center', width: 100 },
        { columnName: 'IM_ZLKZKZDM', prop: 'shejizonglingdaima', label: '涉及总量控制矿种代码', align: 'center', width: 100 },
        { columnName: 'IM_ZLKZKZMC', prop: 'shejizonglingmingc', label: '涉及总量控制矿种名称', align: 'center', width: 100 },
        { columnName: 'IM_GDZB', prop: 'guaidianzuobiao', label: '拐点坐标', align: 'center', minWidth: 140 },
        { columnName: 'IM_ZYLDW', prop: 'ziyuanliangdanwei', label: '资源量单位', align: 'center', minWidth: 140 },
        { columnName: 'IM_TMZYL', prop: 'kaicaiziyuanl', label: '开采主矿种探明资源量', align: 'center', minWidth: 140 },
        { columnName: 'IM_KZZYL', prop: 'kaicaikongzhiliang', label: '开采主矿种控制资源量', align: 'center', minWidth: 140 },
        { columnName: 'IM_TDZYL', prop: 'TDZYL', label: '开采主矿种推断资源量', align: 'center', minWidth: 140 },
        { columnName: 'IM_QTKZJTMZYL', prop: 'qtlaicaitanmingliang', label: '其他开采矿种及探明资源量', align: 'center', minWidth: 140 },
        { columnName: 'IM_QTKZJKZZYL', prop: 'qitakckzkongzhiliang', label: '其他开采矿种及控制资源量', align: 'center', minWidth: 140 },
        { columnName: 'IM_QTKZJTDZYL', prop: 'qtkaicaituiduanliang', label: '其他开采矿种及推断资源量', align: 'center', minWidth: 140 },
        { columnName: 'IM_TFSX', prop: 'toufangshixu', label: '投放时序', align: 'center', minWidth: 140 },
        { columnName: 'IM_BZ', prop: 'remarks', label: '备注', align: 'center', width: 100 },
        { columnName: 'IM_GHQ', prop: 'guihuaqi', label: '规划期', align: 'center', width: 100 },
        { columnName: 'IM_GHBZJB', prop: 'guihuabzlevel', label: '规划编制级别', align: 'center', width: 100 }

  ]
}
