export default function (target) {
  return [
      // 斑地调查
        { columnName: 'wet_BSM', prop: 'baoshima', label: '标识码', align: 'center', width: 100 },
        { columnName: 'wet_YSDM', prop: 'yaosu', label: '要素代码', align: 'center', width: 100 },
        { columnName: 'wet_DQMC', prop: 'diquname', label: '地区名称', align: 'center', width: 100 },
        { columnName: 'wet_QYBM', prop: 'quyubianma', label: '区域编码', align: 'center', minWidth: 100 },
        { columnName: 'wet_SDBKDM', prop: 'shidibk', label: '湿地斑块编码', align: 'center', minWidth: 100 },
        { columnName: 'wet_SDL', prop: 'shidilei', label: '湿地类', align: 'center', width: 100 },
        { columnName: 'wet_SDMJ', prop: 'shidimj', label: '湿地面积', align: 'center', width: 100 },
        { columnName: 'wet_PJHB', prop: 'pjhaiba', label: '平均海拔', align: 'center', width: 100 },
        { columnName: 'wet_SSSLQY', prop: 'suoshusanji', label: '所属三级流域', align: 'center', width: 100 },
        { columnName: 'wet_WD', prop: 'weidu', label: '纬度', align: 'center', width: 100 },
        { columnName: 'wet_JD', prop: 'jingdu', label: '经度', align: 'center', width: 100 },
        { columnName: 'wet_DCR', prop: 'diaocharen', label: '调查人', align: 'center', width: 100 },
        { columnName: 'wet_DCSJ', prop: 'diaochadate', label: '调查时间', align: 'center', width: 100 },

     // 基础土壤
     { columnName: 'base_BSM', prop: 'bsnum', label: '标识码', align: 'center', width: 100 },
     { columnName: 'base_YSDM', prop: 'ysnun', label: '要素代码', align: 'center', width: 100 },
     { columnName: 'base_DQMC', prop: 'diquname', label: '地区名称', align: 'center', width: 100 },
     { columnName: 'base_QYBM', prop: 'qybianhao', label: '区域编码', align: 'center', minWidth: 100 },
     { columnName: 'base_SDBKDM', prop: 'sdbianhao', label: '湿地斑块编码', align: 'center', minWidth: 100 },
     { columnName: 'base_JZLX', prop: 'jztype', label: '基质类型', align: 'center', width: 100 },
     { columnName: 'base_YDH', prop: 'yangdianhao', label: '样点号', align: 'center', width: 100 },
     { columnName: 'base_WD', prop: 'weidu', label: '纬度', align: 'center', width: 100 },
     { columnName: 'base_JD', prop: 'jingdu', label: '经度', align: 'center', width: 100 },
     { columnName: 'base_DCR', prop: 'dcname', label: '调查人', align: 'center', width: 100 },
     { columnName: 'base_DCSJ', prop: 'dcdate', label: '调查时间', align: 'center', width: 100 },
     { columnName: 'base_YJZ', prop: 'youjizhi', label: '有机质（%）', align: 'center', width: 100 },
     { columnName: 'base_NTCHD', prop: 'tnchoudu', label: '泥炭层厚度（cm）', align: 'center', width: 150 },
     { columnName: 'base_PH', prop: 'phzhi', label: 'PH', align: 'center', width: 100 },
     { columnName: 'base_ZD', prop: 'zongdan', label: '总氮（mg/kg）', align: 'center', width: 130 },
     { columnName: 'base_ZL', prop: 'zonglin', label: '总磷', align: 'center', width: 100 },
     { columnName: 'base_TRSRXYZL', prop: 'turang', label: '土壤水溶性盐总量（mg/kg）', align: 'center', width: 180 },

     // 水质
     { columnName: 'water_BSM', prop: 'biaoshima', label: '标识码', align: 'center', width: 100 },
     { columnName: 'water_YSDM', prop: 'yaosudm', label: '要素代码', align: 'center', width: 100 },
     { columnName: 'water_DQMC', prop: 'diquname', label: '地区名称', align: 'center', width: 100 },
     { columnName: 'water_QYBM', prop: 'quyubm', label: '区域编码', align: 'center', minWidth: 100 },
     { columnName: 'water_SDBKDM', prop: 'shibibankuai', label: '湿地斑块编码', align: 'center', minWidth: 100 },
     { columnName: 'water_WD', prop: 'weidu', label: '纬度', align: 'center', width: 100 },
     { columnName: 'water_JD', prop: 'jingdu', label: '经度', align: 'center', width: 100 },
     { columnName: 'water_KHD', prop: 'kuanghuadu', label: '矿化度', align: 'center', width: 100 },
     { columnName: 'water_PH', prop: 'phzhi', label: 'PH', align: 'center', width: 100 },
     { columnName: 'water_RJY', prop: 'rongjieyang', label: '溶解氧(mg/L)', align: 'center', width: 150 },
     { columnName: 'water_WRSHXYL', prop: 'wurishenghua', label: '五日生化需氧量(mg/L)', align: 'center', width: 150 },
     { columnName: 'water_HXXYL', prop: 'huaxueliang', label: '化学需氧量(mg/L)', align: 'center', width: 150 },
     { columnName: 'water_ZD', prop: 'zongdan', label: '总氮（mg/kg）', align: 'center', width: 150 },
     { columnName: 'water_AD', prop: 'andan', label: '氨氮(mg/L)', align: 'center', width: 150 },
     { columnName: 'water_ZL', prop: 'zonglin', label: '总磷', align: 'center', width: 100 },

    // 水文
    { columnName: 'hyd_BSM', prop: 'biaoshima', label: '标识码', align: 'center', width: 100 },
     { columnName: 'hyd_YSDM', prop: 'yaosudaima', label: '要素代码', align: 'center', width: 100 },
     { columnName: 'hyd_DQMC', prop: 'diqumingcheng', label: '地区名称', align: 'center', width: 100 },
     { columnName: 'hyd_QYBM', prop: 'quyubianma', label: '区域编码', align: 'center', minWidth: 100 },
     { columnName: 'hyd_SDBKDM', prop: 'shidibankuai', label: '湿地斑块编码', align: 'center', minWidth: 100 },
     { columnName: 'hyd_SYBJZK', prop: 'shuiyuan', label: '水源补给状况', align: 'center', minWidth: 100 },
     { columnName: 'hyd_SYBJFS', prop: 'shuiyuanbuji', label: '水源补给方式', align: 'center', minWidth: 100 },
     { columnName: 'hyd_PJFS', prop: 'pjshuishen', label: '平均水深', align: 'center', minWidth: 100 },
     { columnName: 'hyd_RLLY', prop: 'ruliuliang', label: '入流流量', align: 'center', minWidth: 100 },
     { columnName: 'hyd_YDH', prop: 'yangdianhao', label: '样点号', align: 'center', minWidth: 100 },
     { columnName: 'hyd_AD', prop: 'andanliang', label: '氨氮(mg/L)', align: 'center', width: 160 },
     { columnName: 'hyd_ZL', prop: 'zonglin', label: '总磷', align: 'center', width: 100 },
     { columnName: 'hyd_WD', prop: 'weidu', label: '纬度', align: 'center', width: 100 },
     { columnName: 'hyd_JD', prop: 'jingdu', label: '经度', align: 'center', width: 100 },
     { columnName: 'hyd_HXXYL', prop: 'huaxueliang', label: '化学需氧量(mg/L)', align: 'center', width: 160 },
     { columnName: 'hyd_ZD', prop: 'zongdan', label: '总氮（mg/kg）', align: 'center', width: 160 },
     { columnName: 'hyd_PH', prop: 'phzhi', label: 'PH', align: 'center', width: 100 },
     { columnName: 'hyd_RJY', prop: 'rongjie', label: '溶解氧(mg/L)', align: 'center', width: 160 },
     { columnName: 'hyd_KHD', prop: 'kuanghuadu', label: '矿化度', align: 'center', width: 100 },
     { columnName: 'hyd_WRSHXYL', prop: 'wurishenghua', label: '五日生化需氧量(mg/L)', align: 'center', width: 160 },
     { columnName: 'hyd_DCR', prop: 'dcname', label: '调查人', align: 'center', width: 100 },
     { columnName: 'hyd_DCSJ', prop: 'dcdate', label: '调查时间', align: 'center', width: 100 },

    // 植物
    { columnName: 'plant_BSM', prop: 'biaoshi', label: '标识码', align: 'center', width: 100 },
    { columnName: 'plant_YSDM', prop: 'yaosu', label: '要素代码', align: 'center', width: 100 },
    { columnName: 'plant_DQMC', prop: 'diqumingcheng', label: '地区名称', align: 'center', width: 100 },
    { columnName: 'plant_QYBM', prop: 'quyubianhao', label: '区域编码', align: 'center', minWidth: 100 },
    { columnName: 'plant_SDBKDM', prop: 'shidibankuai', label: '湿地斑块编码', align: 'center', minWidth: 100 },
    { columnName: 'plant_SDZBMJ', prop: 'shidizbmj', label: '湿地植被面积', align: 'center', width: 100 },
    { columnName: 'plant_DCR', prop: 'dcname', label: '调查人', align: 'center', width: 100 },
    { columnName: 'plant_DCSJ', prop: 'dcdate', label: '调查时间', align: 'center', width: 100 },
    { columnName: 'plant_YSZZWM', prop: 'youshizhong', label: '优势种中文名', align: 'center', width: 100 },
    { columnName: 'plant_YSZLDM', prop: 'yslading', label: '优势种拉丁名', align: 'center', width: 100 },
    { columnName: 'plant_YSZKM', prop: 'yskeming', label: '优势种科名', align: 'center', width: 100 },

    // 动物
    { columnName: 'animal_BSM', prop: 'biaoshima', label: '标识码', align: 'center', width: 100 },
    { columnName: 'animal_YSDM', prop: 'ysdm', label: '要素代码', align: 'center', width: 100 },
    { columnName: 'animal_DQMC', prop: 'diqu', label: '地区名称', align: 'center', width: 100 },
    { columnName: 'animal_QYBM', prop: 'quyu', label: '区域编码', align: 'center', minWidth: 100 },
    { columnName: 'animal_SDBKDM', prop: 'sdbk', label: '湿地斑块编码', align: 'center', minWidth: 100 },
    { columnName: 'animal_DWLX', prop: 'animaltype', label: '动物类型', align: 'center', minWidth: 100 },
    { columnName: 'animal_WD', prop: 'weidu', label: '纬度', align: 'center', width: 100 },
    { columnName: 'animal_JD', prop: 'jingdu', label: '经度', align: 'center', width: 100 },
    { columnName: 'animal_YDH', prop: 'yangdian', label: '样点号', align: 'center', minWidth: 100 },
    { columnName: 'animal_DCR', prop: 'dcrname', label: '调查人', align: 'center', width: 100 },
    { columnName: 'animal_TQZK', prop: 'weather', label: '天气状况', align: 'center', width: 100 },
    { columnName: 'animal_DCQSSJ', prop: 'startime', label: '调查起始时间', align: 'center', width: 100 },
    { columnName: 'animal_DCJSSJ', prop: 'endtime', label: '调查结束时间', align: 'center', width: 100 },
    { columnName: 'animal_ZWM', prop: 'chinaname', label: '中文名', align: 'center', width: 100 },
    { columnName: 'animal_LDM', prop: 'ldm', label: '拉丁名', align: 'center', width: 100 },
    { columnName: 'animal_SL', prop: 'sl', label: '数量', align: 'center', width: 100 },
    { columnName: 'animal_BZ', prop: 'remarks', label: '备注', align: 'center', width: 100 },

    // 保护利用
    { columnName: 'protect_BSM', prop: 'biaoshima', label: '标识码', align: 'center', width: 100 },
    { columnName: 'protect_YSDM', prop: 'yaosu', label: '要素代码', align: 'center', width: 100 },
    { columnName: 'protect_DQMC', prop: 'diquname', label: '地区名称', align: 'center', width: 100 },
    { columnName: 'protect_QYBM', prop: 'quyubianma', label: '区域编码', align: 'center', minWidth: 100 },
    { columnName: 'protect_SDBKDM', prop: 'shidibk', label: '湿地斑块编码', align: 'center', minWidth: 100 },
    { columnName: 'protect_DCSJ', prop: 'dcdate', label: '调查时间', align: 'center', width: 100 },
    { columnName: 'protect_DCR', prop: 'diaocha', label: '调查人', align: 'center', width: 100 },
    { columnName: 'protect_TDQS', prop: 'quanshu', label: '土地权属', align: 'center', width: 100 },
    { columnName: 'protect_ZYLYFS', prop: 'zhuyaoliyong', label: '主要利用方式', align: 'center', width: 100 },
    { columnName: 'protect_SWXLX', prop: 'wxtype', label: '受威胁类型', align: 'center', width: 100 },
    { columnName: 'protect_BHDMC', prop: 'baohudi', label: '保护地名称', align: 'center', width: 100 },
    { columnName: 'protect_BHDMJ', prop: 'baohumj', label: '保护地面积', align: 'center', width: 100 },
    { columnName: 'protect_FJFL', prop: 'leveltype', label: '分级分类', align: 'center', width: 100 }

  ]
}
