export default function (target) {
  return [
      // 斑地调查
        { columnName: 'wet_BSM', prop: 'BSM', label: '标识码', align: 'center', width: 100 },
        { columnName: 'wet_YSDM', prop: 'YSDM', label: '要素代码', align: 'center', width: 100 },
        { columnName: 'wet_DQMC', prop: 'DQMC', label: '地区名称', align: 'center', width: 100 },
        { columnName: 'wet_QYBM', prop: 'QYBM', label: '区域编码', align: 'center', minWidth: 100 },
        { columnName: 'wet_SDBKDM', prop: 'SDBKDM', label: '湿地斑块编码', align: 'center', minWidth: 100 },
        { columnName: 'wet_SDL', prop: 'SDL', label: '湿地类', align: 'center', width: 100 },
        { columnName: 'wet_SDMJ', prop: 'SDMJ', label: '湿地面积', align: 'center', width: 100 },
        { columnName: 'wet_PJHB', prop: 'PJHB', label: '平均海拔', align: 'center', width: 100 },
        { columnName: 'wet_SSSLQY', prop: 'SSSLQY', label: '所属三级流域', align: 'center', width: 100 },
        { columnName: 'wet_WD', prop: 'WD', label: '纬度', align: 'center', width: 100 },
        { columnName: 'wet_JD', prop: 'JD', label: '经度', align: 'center', width: 100 },
        { columnName: 'wet_DCR', prop: 'DCR', label: '调查人', align: 'center', width: 100 },
        { columnName: 'wet_DCSJ', prop: 'DCSJ', label: '调查时间', align: 'center', width: 100 },

     // 基础土壤
     { columnName: 'base_BSM', prop: 'BSM', label: '标识码', align: 'center', width: 100 },
     { columnName: 'base_YSDM', prop: 'YSDM', label: '要素代码', align: 'center', width: 100 },
     { columnName: 'base_DQMC', prop: 'DQMC', label: '地区名称', align: 'center', width: 100 },
     { columnName: 'base_QYBM', prop: 'QYBM', label: '区域编码', align: 'center', minWidth: 100 },
     { columnName: 'base_SDBKDM', prop: 'SDBKDM', label: '湿地斑块编码', align: 'center', minWidth: 100 },
     { columnName: 'base_JZLX', prop: 'JZLX', label: '基质类型', align: 'center', width: 100 },
     { columnName: 'base_YDH', prop: 'YDH', label: '样点号', align: 'center', width: 100 },
     { columnName: 'base_WD', prop: 'WD', label: '纬度', align: 'center', width: 100 },
     { columnName: 'base_JD', prop: 'JD', label: '经度', align: 'center', width: 100 },
     { columnName: 'base_DCR', prop: 'DCR', label: '调查人', align: 'center', width: 100 },
     { columnName: 'base_DCSJ', prop: 'DCSJ', label: '调查时间', align: 'center', width: 100 },
     { columnName: 'base_YJZ', prop: 'YJZ', label: '有机质（%）', align: 'center', width: 100 },
     { columnName: 'base_NTCHD', prop: 'NTCHD', label: '泥炭层厚度（cm）', align: 'center', width: 100 },
     { columnName: 'base_PH', prop: 'PH', label: 'PH', align: 'center', width: 100 },
     { columnName: 'base_ZD', prop: 'ZD', label: '总氮（mg/kg）', align: 'center', width: 100 },
     { columnName: 'base_ZL', prop: 'ZL', label: '总磷', align: 'center', width: 100 },
     { columnName: 'base_TRSRXYZL', prop: 'TRSRXYZL', label: '土壤水溶性盐总量（mg/kg）', align: 'center', width: 100 },

     // 水质
     { columnName: 'water_BSM', prop: 'BSM', label: '标识码', align: 'center', width: 100 },
     { columnName: 'water_YSDM', prop: 'YSDM', label: '要素代码', align: 'center', width: 100 },
     { columnName: 'water_DQMC', prop: 'DQMC', label: '地区名称', align: 'center', width: 100 },
     { columnName: 'water_QYBM', prop: 'QYBM', label: '区域编码', align: 'center', minWidth: 100 },
     { columnName: 'water_SDBKDM', prop: 'SDBKDM', label: '湿地斑块编码', align: 'center', minWidth: 100 },
     { columnName: 'water_WD', prop: 'WD', label: '纬度', align: 'center', width: 100 },
     { columnName: 'water_JD', prop: 'JD', label: '经度', align: 'center', width: 100 },
     { columnName: 'water_KHD', prop: 'KHD', label: '矿化度', align: 'center', width: 100 },
     { columnName: 'water_PH', prop: 'PH', label: 'PH', align: 'center', width: 100 },
     { columnName: 'water_RJY', prop: 'RJY', label: '溶解氧(mg/L)', align: 'center', width: 100 },
     { columnName: 'water_WRSHXYL', prop: 'WRSHXYL', label: '五日生化需氧量(mg/L)', align: 'center', width: 100 },
     { columnName: 'water_HXXYL', prop: 'HXXYL', label: '化学需氧量(mg/L)', align: 'center', width: 100 },
     { columnName: 'water_ZD', prop: 'ZD', label: '总氮（mg/kg）', align: 'center', width: 100 },
     { columnName: 'water_AD', prop: 'AD', label: '氨氮(mg/L)', align: 'center', width: 100 },
     { columnName: 'water_ZL', prop: 'ZL', label: '总磷', align: 'center', width: 100 },

    // 水文
    { columnName: 'hyd_BSM', prop: 'BSM', label: '标识码', align: 'center', width: 100 },
     { columnName: 'hyd_YSDM', prop: 'YSDM', label: '要素代码', align: 'center', width: 100 },
     { columnName: 'hyd_DQMC', prop: 'DQMC', label: '地区名称', align: 'center', width: 100 },
     { columnName: 'hyd_QYBM', prop: 'QYBM', label: '区域编码', align: 'center', minWidth: 100 },
     { columnName: 'hyd_SDBKDM', prop: 'SDBKDM', label: '湿地斑块编码', align: 'center', minWidth: 100 },
     { columnName: 'hyd_SYBJZK', prop: 'SYBJZK', label: '水源补给状况', align: 'center', minWidth: 100 },
     { columnName: 'hyd_SYBJFS', prop: 'SYBJFS', label: '水源补给方式', align: 'center', minWidth: 100 },
     { columnName: 'hyd_PJFS', prop: 'PJFS', label: '平均水深', align: 'center', minWidth: 100 },
     { columnName: 'hyd_RLLY', prop: 'RLLY', label: '入流流量', align: 'center', minWidth: 100 },
     { columnName: 'hyd_YDH', prop: 'YDH', label: '样点号', align: 'center', minWidth: 100 },
     { columnName: 'hyd_AD', prop: 'AD', label: '氨氮(mg/L)', align: 'center', width: 100 },
     { columnName: 'hyd_ZL', prop: 'ZL', label: '总磷', align: 'center', width: 100 },
     { columnName: 'hyd_WD', prop: 'WD', label: '纬度', align: 'center', width: 100 },
     { columnName: 'hyd_JD', prop: 'JD', label: '经度', align: 'center', width: 100 },
     { columnName: 'hyd_HXXYL', prop: 'HXXYL', label: '化学需氧量(mg/L)', align: 'center', width: 100 },
     { columnName: 'hyd_ZD', prop: 'ZD', label: '总氮（mg/kg）', align: 'center', width: 100 },
     { columnName: 'hyd_PH', prop: 'PH', label: 'PH', align: 'center', width: 100 },
     { columnName: 'hyd_RJY', prop: 'RJY', label: '溶解氧(mg/L)', align: 'center', width: 100 },
     { columnName: 'hyd_KHD', prop: 'KHD', label: '矿化度', align: 'center', width: 100 },
     { columnName: 'hyd_WRSHXYL', prop: 'WRSHXYL', label: '五日生化需氧量(mg/L)', align: 'center', width: 100 },
     { columnName: 'hyd_DCR', prop: 'DCR', label: '调查人', align: 'center', width: 100 },
     { columnName: 'hyd_DCSJ', prop: 'DCSJ', label: '调查时间', align: 'center', width: 100 },

    // 植物
    { columnName: 'plant_BSM', prop: 'BSM', label: '标识码', align: 'center', width: 100 },
    { columnName: 'plant_YSDM', prop: 'YSDM', label: '要素代码', align: 'center', width: 100 },
    { columnName: 'plant_DQMC', prop: 'DQMC', label: '地区名称', align: 'center', width: 100 },
    { columnName: 'plant_QYBM', prop: 'QYBM', label: '区域编码', align: 'center', minWidth: 100 },
    { columnName: 'plant_SDBKDM', prop: 'SDBKDM', label: '湿地斑块编码', align: 'center', minWidth: 100 },
    { columnName: 'plant_SDZBMJ', prop: 'SDZBMJ', label: '湿地植被面积', align: 'center', width: 100 },
    { columnName: 'plant_DCR', prop: 'DCR', label: '调查人', align: 'center', width: 100 },
    { columnName: 'plant_DCSJ', prop: 'DCSJ', label: '调查时间', align: 'center', width: 100 },
    { columnName: 'plant_YSZZWM', prop: 'YSZZWM', label: '优势种中文名', align: 'center', width: 100 },
    { columnName: 'plant_YSZLDM', prop: 'YSZLDM', label: '优势种拉丁名', align: 'center', width: 100 },
    { columnName: 'plant_YSZKM', prop: 'YSZKM', label: '优势种科名', align: 'center', width: 100 },

    // 动物
    { columnName: 'animal_BSM', prop: 'BSM', label: '标识码', align: 'center', width: 100 },
    { columnName: 'animal_YSDM', prop: 'YSDM', label: '要素代码', align: 'center', width: 100 },
    { columnName: 'animal_DQMC', prop: 'DQMC', label: '地区名称', align: 'center', width: 100 },
    { columnName: 'animal_QYBM', prop: 'QYBM', label: '区域编码', align: 'center', minWidth: 100 },
    { columnName: 'animal_SDBKDM', prop: 'SDBKDM', label: '湿地斑块编码', align: 'center', minWidth: 100 },
    { columnName: 'animal_DWLX', prop: 'DWLX', label: '动物类型', align: 'center', minWidth: 100 },
    { columnName: 'animal_WD', prop: 'WD', label: '纬度', align: 'center', width: 100 },
    { columnName: 'animal_JD', prop: 'JD', label: '经度', align: 'center', width: 100 },
    { columnName: 'animal_YDH', prop: 'YDH', label: '样点号', align: 'center', minWidth: 100 },
    { columnName: 'animal_DCR', prop: 'DCR', label: '调查人', align: 'center', width: 100 },
    { columnName: 'animal_TQZK', prop: 'TQZK', label: '天气状况', align: 'center', width: 100 },
    { columnName: 'animal_DCQSSJ', prop: 'DCQSSJ', label: '调查起始时间', align: 'center', width: 100 },
    { columnName: 'animal_DCJSSJ', prop: 'DCJSSJ', label: '调查结束时间', align: 'center', width: 100 },
    { columnName: 'animal_ZWM', prop: 'ZWM', label: '中文名', align: 'center', width: 100 },
    { columnName: 'animal_LDM', prop: 'LDM', label: '拉丁名', align: 'center', width: 100 },
    { columnName: 'animal_SL', prop: 'SL', label: '数量', align: 'center', width: 100 },
    { columnName: 'animal_BZ', prop: 'BZ', label: '备注', align: 'center', width: 100 },

    // 保护利用
    { columnName: 'protect_BSM', prop: 'BSM', label: '标识码', align: 'center', width: 100 },
    { columnName: 'protect_YSDM', prop: 'YSDM', label: '要素代码', align: 'center', width: 100 },
    { columnName: 'protect_DQMC', prop: 'DQMC', label: '地区名称', align: 'center', width: 100 },
    { columnName: 'protect_QYBM', prop: 'QYBM', label: '区域编码', align: 'center', minWidth: 100 },
    { columnName: 'protect_SDBKDM', prop: 'SDBKDM', label: '湿地斑块编码', align: 'center', minWidth: 100 },
    { columnName: 'protect_DCSJ', prop: 'DCSJ', label: '调查时间', align: 'center', width: 100 },
    { columnName: 'protect_DCR', prop: 'DCR', label: '调查人', align: 'center', width: 100 },
    { columnName: 'protect_TDQS', prop: 'TDQS', label: '土地权属', align: 'center', width: 100 },
    { columnName: 'protect_ZYLYFS', prop: 'ZYLYFS', label: '主要利用方式', align: 'center', width: 100 },
    { columnName: 'protect_SWXLX', prop: 'SWXLX', label: '受威胁类型', align: 'center', width: 100 },
    { columnName: 'protect_BHDMC', prop: 'BHDMC', label: '保护地名称', align: 'center', width: 100 },
    { columnName: 'protect_BHDMJ', prop: 'BHDMJ', label: '保护地面积', align: 'center', width: 100 },
    { columnName: 'protect_FJFL', prop: 'FJFL', label: '分级分类', align: 'center', width: 100 }

  ]
}
